---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  # worker node 1 created
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongosecret 
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongosecret 
              key: mongo-root-password
---
# Mongo DB Service 생성
kind: Service
apiVersion: v1
metadata:
  name: mongodb-svc
  labels:
    app: mongodb
spec:
  type: ClusterIP
  # clusterIP: 10.100.10.10
  selector:
    app: mongodb
  ports:
  # MongoDB Default Port 지정
  - protocol: TCP
    port: 27017
    targetPort: 27017