---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        # Admin Username 정보
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: mongo-root-username
        # Admin UserPassword 정보
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongosecret
              key: mongo-root-password
        # MongoDB URL Mapping
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
# Mongo-Express Service 생성
kind: Service
apiVersion: v1
metadata: 
  name: mongodb-express-svc
  labels:
    app: mongo-express
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000