---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod-resources
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 4
        memory: 500Mi
      # limits:
      #   cpu: 6
      #   memory: 500Mi