---
# pod 생성
kind: Pod
apiVersion: v1
metadata:
  name: genid-stone
spec:
  containers:
  - name: fakeid
    image: ckim96/genid
    envFrom:
      - configMapRef:
          name: test-config
    # /webdata 경로 genid 값을 가져옴
    volumeMounts:
    - name: html
      mountPath: /webdata
  - name: web-server 
    image: nginx:1.14
    ports:
    # Port 80 제공
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    emptyDir: {}
