---
kind: IPAddressPool
apiVersion: metallb.io/v1beta1
metadata:
  name: lb-pool
  namespace: metallb-system   
spec:
  addresses:
  - 192.168.1.50-192.168.1.60

---
kind: L2Advertisement
apiVersion: metallb.io/v1beta1
metadata:
  name: example
  namespace: metallb-system   
