---
# blue Deployment (POD x 3)
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webui-blue
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: web
      version: blue
  template:
    metadata:
      name: webui-blue-pod
      labels:
        app: web
        version: blue
    spec:
      containers:
      - name: webui-blue-container
        image: whatwant/node-web:2.0
        ports:
        - containerPort: 80
