---
kind: Pod
apiVersion: v1
metadata:
  # metadata name
  name: mongodb-pod
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
    - containerPort: 27017
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: backend-mongo
        topologyKey: kubernetes.io/hostname