---
kind: CertificateSigningRequest
apiVersion: certificates.k8s.io/v1
metadata:
  name: myuser
spec:
  # myuser.csr 있는 aes 값을 읽어온 후, base64 방식으로 decoding을 진행한다.
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0diWGwxYzJWeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXFTbmQveU53L3lrYndnc0hoS2V4Q094VXhyVUYwSlQ1YXpESTVsWURMZC9YCllJdTkyRXFnNDJwclNGUWdzYkRKL09YNTNSdThVWVN2VlRsVm5rbmFjRTEyN2tHWnRXdnVvZXlZdCs3WHlOMzgKVTM1SDhoanZCckVRNlpzcVJnMWp6Yk5PUmdOVXo5MHUzNTF5aE80anB6S0llZE1LTnpKT1kxTWxVNWo1N2U4NgozRUxKNzhLc0FwUzVVQVpJTllYVHB6U3FQUFA5V29jNHNGd0FiTkZNb0x6NktZQ05xdWJwOThqT0ozWEp4UWJiClBNMXc0SEdJSVZKNUFuWXJSaG1YZXlGSThaMzd3aitmUTUwRS93eHZoM0hVbU5ubVBhTnVObEdCemtvMURnYVgKSVgxclV2U1hGRFRlNWV2ektFS01UOHpuM1pPNkpQVnVidE5CTXJXV0t3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBS1hmU3lneFhjbEVVUFBob2xycDgxZjhzTVRQSjJPOTFxcC9uckZSM2NkTFcvTThwenp6CjNXVFU0UFMwL2V6MWYwL2ZZMTFKTEtjcy9RZVcxRXNMQXpzam45N3N1OThFMXpxTVQxQjNsZExtVHIyY0czK1EKelVEdGx4L3UrOUlZU2xyNjdSZ0tya3BFN3ZVWlFrQ3A0Q2x6Yy80MXdmaVFXWWxCekdLSVRQTFg2dlV0K1k3Vwp0Ny8vMmY1bTZCWlU3VzQxTmJqZzk5Ry95T3llZ0lxVkNJTncvcmtNV3NWTG1QcG5RbFZPOHQ5SlFjVlRDQ2p4CkV0UGtES1FXTlFnRlFGQUIvS3VhQ0hMOTRiWEVlbE9zNUZkRWhQcmtKZjU1ZGg3RDZuRXNrb1ZGZEF0UnhNM1MKd2VWM0V0QVhybEFMODJNZkJDTTUxSkZxQWo3c0JhbW01NEE9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 864000  
  usages:
  - client auth
