---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-adminer-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgres-adminer
  template:
    metadata:
      labels:
        app: postgres-adminer
    spec:
      containers:
      - name: postgres-adminer-container
        image: adminer
        ports:
        - containerPort: 8080
---
# postgres-adminior service
kind: Service
apiVersion: v1
metadata:
  name: postgres-adminior-svc
spec:
  type: LoadBalancer
  selector:
    app: postgres-adminer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000