---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgre-deploy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_password
---
# postgres service
kind: Service
apiVersion: v1
metadata: 
  name: postgres-svc
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432